import {
    Wrench,
    Monitor,
    Car,
    Hammer,
    Building,
    Server,
    ShieldCheck,
    Armchair,
    Laptop,
    Printer,
    Phone,
    Wifi,
    Camera,
    Lightbulb,
    Fan,
    Thermometer,
    Droplets,
    Zap,
    Cog,
    Package,
    Box,
    Archive,
    Briefcase,
    Clock,
    Key,
    Lock,
    MapPin,
    Truck,
    Plane,
    Ship,
    Bike,
    HeartPulse,
    Stethoscope,
    Syringe,
    Pill,
    FlaskConical,
    Microscope,
    GraduationCap,
    BookOpen,
    PenTool,
    Scissors,
    Paintbrush,
    Music,
    Headphones,
    Speaker,
    Tv,
    Gamepad,
    Dumbbell,
    Trophy,
    Utensils,
    Coffee,
    ShoppingCart,
    CreditCard,
    Banknote,
    BarChart,
    PieChart,
    FileText,
    FolderOpen,
    HardDrive,
    Cpu,
    MemoryStick,
    Router,
    Cable,
    Battery,
    Plug,
    type LucideIcon,
} from 'lucide-react';

// Map of icon names to Lucide components
const ICON_MAP: Record<string, LucideIcon> = {
    Wrench,
    Monitor,
    Car,
    Hammer,
    Building,
    Server,
    ShieldCheck,
    Armchair,
    Laptop,
    Printer,
    Phone,
    Wifi,
    Camera,
    Lightbulb,
    Fan,
    Thermometer,
    Droplets,
    Zap,
    Cog,
    Package,
    Box,
    Archive,
    Briefcase,
    Clock,
    Key,
    Lock,
    MapPin,
    Truck,
    Plane,
    Ship,
    Bike,
    HeartPulse,
    Stethoscope,
    Syringe,
    Pill,
    FlaskConical,
    Microscope,
    GraduationCap,
    BookOpen,
    PenTool,
    Scissors,
    Paintbrush,
    Music,
    Headphones,
    Speaker,
    Tv,
    Gamepad,
    Dumbbell,
    Trophy,
    Utensils,
    Coffee,
    ShoppingCart,
    CreditCard,
    Banknote,
    BarChart,
    PieChart,
    FileText,
    FolderOpen,
    HardDrive,
    Cpu,
    MemoryStick,
    Router,
    Cable,
    Battery,
    Plug,
};

/**
 * Get the Lucide icon component for an asset type
 * @param iconName - The name of the icon (e.g., "Wrench", "Monitor")
 * @returns The Lucide icon component, or Package as default
 */
export const getAssetTypeIcon = (iconName?: string | null): LucideIcon => {
    if (!iconName) return Package;
    return ICON_MAP[iconName] || Package;
};

/**
 * Get all available icon names
 */
export const getAvailableIconNames = (): string[] => {
    return Object.keys(ICON_MAP);
};

export { ICON_MAP };
